version: 2.1
orbs:
  orb-tools: circleci/orb-tools@8.27.4
jobs:
  integration-tests:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run: echo TODO
workflows:
  integration-tests_prod-release:
    jobs:
      - integration-tests:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /integration-.*/
          name: integration-tests-dev
      - integration-tests:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-.*/
          name: integration-tests-master
      - orb-tools/dev-promote-prod:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-patch.*/
          name: dev-promote-patch
          orb-name: bottech/kubernetes-diagnostics
          requires:
            - integration-tests-master
      - orb-tools/dev-promote-prod:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-minor.*/
          name: dev-promote-minor
          orb-name: bottech/kubernetes-diagnostics
          release: minor
          requires:
            - integration-tests-master
      - orb-tools/dev-promote-prod:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-major.*/
          name: dev-promote-major
          orb-name: bottech/kubernetes-diagnostics
          release: major
          requires:
            - integration-tests-master
  publish-dev:
    jobs:
      - orb-tools/lint:
          lint-dir: src
      - orb-tools/pack:
          artifact-path: target
          requires:
            - orb-tools/lint
      - orb-tools/publish-dev:
          orb-name: bottech/kubernetes-diagnostics
          requires:
            - orb-tools/pack
      - orb-tools/trigger-integration-workflow:
          filters:
            branches:
              ignore: master
          name: trigger-integration-dev
          requires:
            - orb-tools/publish-dev
          ssh-fingerprints: 7d:5a:30:7b:f0:54:fb:31:da:97:74:e7:35:76:0b:07
      - orb-tools/trigger-integration-workflow:
          filters:
            branches:
              only: master
          name: trigger-integration-master
          requires:
            - orb-tools/publish-dev
          ssh-fingerprints: 7d:5a:30:7b:f0:54:fb:31:da:97:74:e7:35:76:0b:07
          tag: master
